/*
    Don't edit this file!
    It's autogenerated on builds
*/
import { library, icon, dom } from '@fortawesome/fontawesome-svg-core';
import { faBan } from '@fortawesome/pro-solid-svg-icons/faBan';
import { faBars } from '@fortawesome/pro-solid-svg-icons/faBars';
import { faBeer } from '@fortawesome/pro-solid-svg-icons/faBeer';
import { faBook } from '@fortawesome/pro-solid-svg-icons/faBook';
import { faBrowser } from '@fortawesome/pro-solid-svg-icons/faBrowser';
import { faCheck } from '@fortawesome/pro-solid-svg-icons/faCheck';
import { faCircleNotch } from '@fortawesome/pro-solid-svg-icons/faCircleNotch';
import { faClock } from '@fortawesome/pro-solid-svg-icons/faClock';
import { faCloudDownloadAlt } from '@fortawesome/pro-solid-svg-icons/faCloudDownloadAlt';
import { faCloudUpload } from '@fortawesome/pro-solid-svg-icons/faCloudUpload';
import { faCloudUploadAlt } from '@fortawesome/pro-solid-svg-icons/faCloudUploadAlt';
import { faCookie } from '@fortawesome/pro-solid-svg-icons/faCookie';
import { faDownload } from '@fortawesome/pro-solid-svg-icons/faDownload';
import { faEdit } from '@fortawesome/pro-solid-svg-icons/faEdit';
import { faEnvelope } from '@fortawesome/pro-solid-svg-icons/faEnvelope';
import { faEyeSlash } from '@fortawesome/pro-solid-svg-icons/faEyeSlash';
import { faGlobe } from '@fortawesome/pro-solid-svg-icons/faGlobe';
import { faHeart } from '@fortawesome/pro-solid-svg-icons/faHeart';
import { faHome } from '@fortawesome/pro-solid-svg-icons/faHome';
import { faKey } from '@fortawesome/pro-solid-svg-icons/faKey';
import { faListUl } from '@fortawesome/pro-solid-svg-icons/faListUl';
import { faNewspaper } from '@fortawesome/pro-solid-svg-icons/faNewspaper';
import { faPlus } from '@fortawesome/pro-solid-svg-icons/faPlus';
import { faPlusSquare } from '@fortawesome/pro-solid-svg-icons/faPlusSquare';
import { faPowerOff } from '@fortawesome/pro-solid-svg-icons/faPowerOff';
import { faPuzzlePiece } from '@fortawesome/pro-solid-svg-icons/faPuzzlePiece';
import { faQuestion } from '@fortawesome/pro-solid-svg-icons/faQuestion';
import { faQuestionCircle } from '@fortawesome/pro-solid-svg-icons/faQuestionCircle';
import { faRedo } from '@fortawesome/pro-solid-svg-icons/faRedo';
import { faSave } from '@fortawesome/pro-solid-svg-icons/faSave';
import { faServer } from '@fortawesome/pro-solid-svg-icons/faServer';
import { faSignIn } from '@fortawesome/pro-solid-svg-icons/faSignIn';
import { faSort } from '@fortawesome/pro-solid-svg-icons/faSort';
import { faSync } from '@fortawesome/pro-solid-svg-icons/faSync';
import { faTag } from '@fortawesome/pro-solid-svg-icons/faTag';
import { faTrash } from '@fortawesome/pro-solid-svg-icons/faTrash';
import { faUser } from '@fortawesome/pro-solid-svg-icons/faUser';
import { faBitcoin } from '@fortawesome/free-brands-svg-icons/faBitcoin';
import { faDiscord } from '@fortawesome/free-brands-svg-icons/faDiscord';
import { faPaypal } from '@fortawesome/free-brands-svg-icons/faPaypal';

export function initFA(): void {
    library.add(faBan,
        faBars,
        faBeer,
        faBitcoin,
        faBook,
        faBrowser,
        faCheck,
        faCircleNotch,
        faClock,
        faCloudDownloadAlt,
        faCloudUpload,
        faCloudUploadAlt,
        faCookie,
        faDiscord,
        faDownload,
        faEdit,
        faEnvelope,
        faEyeSlash,
        faGlobe,
        faHeart,
        faHome,
        faKey,
        faListUl,
        faNewspaper,
        faPaypal,
        faPlus,
        faPlusSquare,
        faPowerOff,
        faPuzzlePiece,
        faQuestion,
        faQuestionCircle,
        faRedo,
        faSave,
        faServer,
        faSignIn,
        faSort,
        faSync,
        faTag,
        faTrash,
        faUser
    );
    dom.watch();
}