import { library, dom } from '@fortawesome/fontawesome';
import { faClock } from '@fortawesome/pro-solid-svg-icons';
import { faUser } from '@fortawesome/pro-solid-svg-icons';
import { faServer } from '@fortawesome/pro-solid-svg-icons';
import { faBeer } from '@fortawesome/pro-solid-svg-icons';
import { faBook } from '@fortawesome/pro-solid-svg-icons';
import { faBars } from '@fortawesome/pro-solid-svg-icons';
import { faEyeSlash } from '@fortawesome/pro-solid-svg-icons';
import { faReload } from '@fortawesome/pro-solid-svg-icons';
import { faHelpCircle } from '@fortawesome/pro-solid-svg-icons';
import { faBan } from '@fortawesome/pro-solid-svg-icons';
import { faCheck } from '@fortawesome/pro-solid-svg-icons';
import { faCircleNotch } from '@fortawesome/pro-solid-svg-icons';
import { faPowerOff } from '@fortawesome/pro-solid-svg-icons';
import { faDownload } from '@fortawesome/pro-solid-svg-icons';
import { faTag } from '@fortawesome/pro-solid-svg-icons';
import { faPuzzlePiece } from '@fortawesome/pro-solid-svg-icons';
import { faPlus } from '@fortawesome/pro-solid-svg-icons';
import { faSave } from '@fortawesome/pro-solid-svg-icons';
import { faBrowser } from '@fortawesome/pro-solid-svg-icons';
import { faKey } from '@fortawesome/pro-solid-svg-icons';
import { faTrash } from '@fortawesome/pro-solid-svg-icons';
import { faQuestion } from '@fortawesome/pro-solid-svg-icons';
import { faListUl } from '@fortawesome/pro-solid-svg-icons';
import { faGlobe } from '@fortawesome/pro-solid-svg-icons';
import { faEnvelope } from '@fortawesome/pro-solid-svg-icons';
import { faHeart } from '@fortawesome/pro-solid-svg-icons';
import { faSort } from '@fortawesome/pro-solid-svg-icons';
import { faCloudDownloadAlt } from '@fortawesome/pro-solid-svg-icons';
import { faSignIn } from '@fortawesome/pro-solid-svg-icons';
import { faPlusSquare } from '@fortawesome/pro-solid-svg-icons';
import { faDiscord } from '@fortawesome/pro-brands-svg-icons';
import { faPaypal } from '@fortawesome/pro-brands-svg-icons';
import { faBitcoin } from '@fortawesome/pro-brands-svg-icons';

export function initFA(): void { library.add(faClock,faUser,faServer,faBeer,faBook,faBars,faEyeSlash,faReload,faHelpCircle,faBan,faCheck,faCircleNotch,faPowerOff,faDownload,faTag,faPuzzlePiece,faPlus,faSave,faBrowser,faKey,faTrash,faQuestion,faListUl,faGlobe,faEnvelope,faHeart,faSort,faCloudDownloadAlt,faSignIn,faPlusSquare,faDiscord,faPaypal,faBitcoin); }